### PR TITLE
feat: base acapy docs

### PR DESCRIPTION
**Pull request by amanji**

### CODE REVIEW

**Comment by swcurran** [comment]
Also -- the PR is not DCO signed, so that needs to be fixed before merging -- DCO - Developer Certificate of Origin - https://github.com/apps/dco.

**Comment by swcurran** [comment]
Also, a little concerned about the size of the commit after I generated the docs. Does it make sense that there should be 10K plus files to add to the repo?  Looks like the .gitignore might need to be improved.  For example, I see a pile of build assets, and a `node_modules` folder included.

**Comment by amanji** [comment]
There should be a .gitignore in the repo to exclude node_modules and built files. The original docs should only be about ~400 files and most of those are the `.rst` and generated docstrings.

**Comment by swcurran** [comment]
The “build-docs” fails when used with a `-t <tag> -m` and the corresponding modifications file doesn’t exist.  Should have a check first to see if the file exists.

**Comment by swcurran** [comment]
Good stuff — I’ll give it another try.

**Comment by swcurran** [comment]
Looking better.  Notes:

- Ran `yarn` first and that worked. There was an extra file created - `yarn.lock` -- should probably be checked in or .gitignored.
- Running `build-docs` gives this error:

```
./manage build-docs -t 0.7.5
3.4.1
➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ trim@npm:0.0.1 is deprecated: Use String.prototype.trim() instead
➤ YN0002: │ @docsearch/react@npm:3.3.3 [50daf] doesn't provide @algolia/client-search (pae697), requested by @algolia/autocomplete-preset-algolia
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 8s 272ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 8s 356ms
```

- On first run `yarn start` -- I got a big ugly error on the website. Closing it allowed proceeding.
- Lots of errors in the log as I ran.
- Flipping between the versions didn't work too well.

Looking good!  We'll talk tomorrow and decide on if we can merge and evolve from there.  I do have some questions those...

:-).

**Review by swcurran — APPROVED** [review]
Close enough. There is still some clean-up, but let's give this a try.

**Pull request merged**
